version: "3.6"
services:
  mongo:
    image: mongo:2.6
    container_name: ${DBHOST}
    hostname: mongo
    expose:
    - "27017"
    ports:
    - "27017:27017"
    
    network_mode: ${NETWORKMODE}
  orion:
    image: fiware/orion:latest
    container_name: ${ORIONHOST}
    hostname: orion
    depends_on:
      - mongo
    links:
    - mongo
    network_mode: ${NETWORKMODE}
    ports:
    - "1026:1026"
    command: -dbhost ${DBHOST}
  iot-agent:
    image: fiware/iotagent-json:latest
    hostname: iot-agent
    container_name: thesis-iota-json
    depends_on:
        - mongo
        - orion
    links:
    - mongo
    network_mode: ${NETWORKMODE}
    expose:
        - "4041"
        - "7896"
    ports:
        - "4041:4041"
        - "7896:7896"
    environment:
        - IOTA_CB_HOST=${ORIONHOST}
        - IOTA_CB_PORT=1026
        - IOTA_NORTH_PORT=4041
        - IOTA_REGISTRY_TYPE=mongodb
        - IOTA_LOG_LEVEL=DEBUG
        - IOTA_TIMESTAMP=true
        - IOTA_CB_NGSI_VERSION=v2
        - IOTA_AUTOCAST=true
        - IOTA_MONGO_HOST=${DBHOST}
        - IOTA_MONGO_PORT=27017
        - IOTA_MONGO_DB=${JSONCOLLECTION}
        - IOTA_HTTP_PORT=7896
        - IOTA_PROVIDER_URL=http://iot-agent:4041
        - IOTA_DEFAULT_RESOURCE=/iot/json
