//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FIWAREHub.Models.Sql
{

    public partial class ClusterCentroid : XPObject
    {
        QuarterlyPeriod fQuarterlyPeriod;
        [Association(@"ClusterCentroidReferencesClusterPeriodCollection")]
        public QuarterlyPeriod QuarterlyPeriod
        {
            get { return fQuarterlyPeriod; }
            set { SetPropertyValue<QuarterlyPeriod>(nameof(QuarterlyPeriod), ref fQuarterlyPeriod, value); }
        }
        double fLatitude;
        public double Latitude
        {
            get { return fLatitude; }
            set { SetPropertyValue<double>(nameof(Latitude), ref fLatitude, value); }
        }
        double fLongitude;
        public double Longitude
        {
            get { return fLongitude; }
            set { SetPropertyValue<double>(nameof(Longitude), ref fLongitude, value); }
        }
    }

}
