//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FIWAREHub.Models.Sql
{

    public partial class QuarterlyPeriod : XPObject
    {
        string fState;
        public string State
        {
            get { return fState; }
            set { SetPropertyValue<string>(nameof(State), ref fState, value); }
        }
        DateTime fDateFrom;
        public DateTime DateFrom
        {
            get { return fDateFrom; }
            set { SetPropertyValue<DateTime>(nameof(DateFrom), ref fDateFrom, value); }
        }
        DateTime fDateTo;
        public DateTime DateTo
        {
            get { return fDateTo; }
            set { SetPropertyValue<DateTime>(nameof(DateTo), ref fDateTo, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        int fQuarter;
        public int Quarter
        {
            get { return fQuarter; }
            set { SetPropertyValue<int>(nameof(Quarter), ref fQuarter, value); }
        }
        int fYear;
        public int Year
        {
            get { return fYear; }
            set { SetPropertyValue<int>(nameof(Year), ref fYear, value); }
        }
        [Association(@"ClusterCentroidReferencesClusterPeriodCollection"), Aggregated]
        public XPCollection<ClusterCentroid> ClusterCentroids { get { return GetCollection<ClusterCentroid>(nameof(ClusterCentroids)); } }
    }

}
