//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FIWAREHub.Models.Sql
{

    public partial class SyncOperation : XPObject
    {
        DateTime? fDateStarted;
        public DateTime? DateStarted
        {
            get { return fDateStarted; }
            set { SetPropertyValue<DateTime?>(nameof(DateStarted), ref fDateStarted, value); }
        }
        DateTime? fDateFinished;
        public DateTime? DateFinished
        {
            get { return fDateFinished; }
            set { SetPropertyValue<DateTime?>(nameof(DateFinished), ref fDateFinished, value); }
        }
        DateTime? fDateModified;
        public DateTime? DateModified
        {
            get { return fDateModified; }
            set { SetPropertyValue<DateTime?>(nameof(DateModified), ref fDateModified, value); }
        }
        int? fIterations;
        public int? Iterations
        {
            get { return fIterations; }
            set { SetPropertyValue<int?>(nameof(Iterations), ref fIterations, value); }
        }
    }

}
