//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FIWAREHub.Models.Sql
{

    public partial class SyncOperationException : XPObject
    {
        SyncOperation fSyncOperation;
        [Association(@"SyncOperationExceptionReferencesSyncOperation")]
        public SyncOperation SyncOperation
        {
            get { return fSyncOperation; }
            set { SetPropertyValue<SyncOperation>(nameof(SyncOperation), ref fSyncOperation, value); }
        }
        string fMessage;
        [Size(SizeAttribute.Unlimited)]
        public string Message
        {
            get { return fMessage; }
            set { SetPropertyValue<string>(nameof(Message), ref fMessage, value); }
        }
        DateTime fDateOccurred;
        public DateTime DateOccurred
        {
            get { return fDateOccurred; }
            set { SetPropertyValue<DateTime>(nameof(DateOccurred), ref fDateOccurred, value); }
        }
    }

}
