//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FIWAREHub.Models.Sql
{

    public partial class SyncOperation : XPObject
    {
        Guid fUniqueId;
        public Guid UniqueId
        {
            get { return fUniqueId; }
            set { SetPropertyValue<Guid>(nameof(UniqueId), ref fUniqueId, value); }
        }
        DateTime fDateStarted;
        public DateTime DateStarted
        {
            get { return fDateStarted; }
            set { SetPropertyValue<DateTime>(nameof(DateStarted), ref fDateStarted, value); }
        }
        DateTime? fDateFinished;
        public DateTime? DateFinished
        {
            get { return fDateFinished; }
            set { SetPropertyValue<DateTime?>(nameof(DateFinished), ref fDateFinished, value); }
        }
        DateTime? fDateModified;
        public DateTime? DateModified
        {
            get { return fDateModified; }
            set { SetPropertyValue<DateTime?>(nameof(DateModified), ref fDateModified, value); }
        }
        long? fCurrentItem;
        public long? CurrentItem
        {
            get { return fCurrentItem; }
            set { SetPropertyValue<long?>(nameof(CurrentItem), ref fCurrentItem, value); }
        }
        long? fTotalItemCount;
        public long? TotalItemCount
        {
            get { return fTotalItemCount; }
            set { SetPropertyValue<long?>(nameof(TotalItemCount), ref fTotalItemCount, value); }
        }
        double? fProgressPercentage;
        public double? ProgressPercentage
        {
            get { return fProgressPercentage; }
            set { SetPropertyValue<double?>(nameof(ProgressPercentage), ref fProgressPercentage, value); }
        }
        bool fIsRunning;
        public bool IsRunning
        {
            get { return fIsRunning; }
            set { SetPropertyValue<bool>(nameof(IsRunning), ref fIsRunning, value); }
        }
        [Association(@"SyncOperationExceptionReferencesSyncOperation"), Aggregated]
        public XPCollection<SyncOperationException> SyncOperationExceptions { get { return GetCollection<SyncOperationException>(nameof(SyncOperationExceptions)); } }
    }

}
