//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FIWAREHub.Models.Sql
{

    public partial class WeatherReport : XPObject
    {
        decimal fHumidity;
        public decimal Humidity
        {
            get { return fHumidity; }
            set { SetPropertyValue<decimal>(nameof(Humidity), ref fHumidity, value); }
        }
    }

}
