//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FIWAREHub.Models.Sql
{

    public partial class WeatherReport : XPObject
    {
        long fUID;
        public long UID
        {
            get { return fUID; }
            set { SetPropertyValue<long>(nameof(UID), ref fUID, value); }
        }
        string fDeviceId;
        public string DeviceId
        {
            get { return fDeviceId; }
            set { SetPropertyValue<string>(nameof(DeviceId), ref fDeviceId, value); }
        }
        DateTime? fReportTime;
        public DateTime? ReportTime
        {
            get { return fReportTime; }
            set { SetPropertyValue<DateTime?>(nameof(ReportTime), ref fReportTime, value); }
        }
        string fWeatherEvent;
        public string WeatherEvent
        {
            get { return fWeatherEvent; }
            set { SetPropertyValue<string>(nameof(WeatherEvent), ref fWeatherEvent, value); }
        }
        string fSeverity;
        public string Severity
        {
            get { return fSeverity; }
            set { SetPropertyValue<string>(nameof(Severity), ref fSeverity, value); }
        }
        string fOriginalWeatherDescription;
        [Size(SizeAttribute.Unlimited)]
        public string OriginalWeatherDescription
        {
            get { return fOriginalWeatherDescription; }
            set { SetPropertyValue<string>(nameof(OriginalWeatherDescription), ref fOriginalWeatherDescription, value); }
        }
        double? fTemperature;
        public double? Temperature
        {
            get { return fTemperature; }
            set { SetPropertyValue<double?>(nameof(Temperature), ref fTemperature, value); }
        }
        double? fHumidity;
        public double? Humidity
        {
            get { return fHumidity; }
            set { SetPropertyValue<double?>(nameof(Humidity), ref fHumidity, value); }
        }
        double? fPressure;
        public double? Pressure
        {
            get { return fPressure; }
            set { SetPropertyValue<double?>(nameof(Pressure), ref fPressure, value); }
        }
        double? fVisibility;
        public double? Visibility
        {
            get { return fVisibility; }
            set { SetPropertyValue<double?>(nameof(Visibility), ref fVisibility, value); }
        }
        string fCloudCoverage;
        public string CloudCoverage
        {
            get { return fCloudCoverage; }
            set { SetPropertyValue<string>(nameof(CloudCoverage), ref fCloudCoverage, value); }
        }
        string fWindDirection;
        public string WindDirection
        {
            get { return fWindDirection; }
            set { SetPropertyValue<string>(nameof(WindDirection), ref fWindDirection, value); }
        }
        double? fWindChill;
        public double? WindChill
        {
            get { return fWindChill; }
            set { SetPropertyValue<double?>(nameof(WindChill), ref fWindChill, value); }
        }
        double? fWindSpeed;
        public double? WindSpeed
        {
            get { return fWindSpeed; }
            set { SetPropertyValue<double?>(nameof(WindSpeed), ref fWindSpeed, value); }
        }
        double? fPrecipitation;
        public double? Precipitation
        {
            get { return fPrecipitation; }
            set { SetPropertyValue<double?>(nameof(Precipitation), ref fPrecipitation, value); }
        }
        string fCity;
        public string City
        {
            get { return fCity; }
            set { SetPropertyValue<string>(nameof(City), ref fCity, value); }
        }
        string fCounty;
        public string County
        {
            get { return fCounty; }
            set { SetPropertyValue<string>(nameof(County), ref fCounty, value); }
        }
        string fState;
        public string State
        {
            get { return fState; }
            set { SetPropertyValue<string>(nameof(State), ref fState, value); }
        }
        string fZipCode;
        public string ZipCode
        {
            get { return fZipCode; }
            set { SetPropertyValue<string>(nameof(ZipCode), ref fZipCode, value); }
        }
        string fCountry;
        public string Country
        {
            get { return fCountry; }
            set { SetPropertyValue<string>(nameof(Country), ref fCountry, value); }
        }
    }

}
